/**
 * Nacionalidades aceitas no cadastro de quem se inscreve SEM CPF.
 *
 * O Brasil NAO esta na lista, de proposito: brasileiro se inscreve com CPF,
 * obrigatoriamente. A opcao sem CPF existe para estrangeiro -- decisao do
 * Patrick em 13/09/2026, e e por isso que o interruptor da tela de
 * verificacao passou a dizer "Sou estrangeiro" em vez de "Nao tenho CPF".
 *
 * Nomes em portugues, gerados do padrao ISO 3166-1 alpha-2 com
 * Intl.DisplayNames('pt-BR') e ordenados em pt-BR. Na coluna
 * `nacionalidade` guardamos o CODIGO ISO, nao o nome: nome de pais muda,
 * codigo nao.
 */
export const NACIONALIDADES = [
  { iso: 'AF', nome: 'Afeganistão' },
  { iso: 'ZA', nome: 'África do Sul' },
  { iso: 'AL', nome: 'Albânia' },
  { iso: 'DE', nome: 'Alemanha' },
  { iso: 'AD', nome: 'Andorra' },
  { iso: 'AO', nome: 'Angola' },
  { iso: 'AG', nome: 'Antígua e Barbuda' },
  { iso: 'SA', nome: 'Arábia Saudita' },
  { iso: 'DZ', nome: 'Argélia' },
  { iso: 'AR', nome: 'Argentina' },
  { iso: 'AM', nome: 'Armênia' },
  { iso: 'AU', nome: 'Austrália' },
  { iso: 'AT', nome: 'Áustria' },
  { iso: 'AZ', nome: 'Azerbaijão' },
  { iso: 'BS', nome: 'Bahamas' },
  { iso: 'BD', nome: 'Bangladesh' },
  { iso: 'BB', nome: 'Barbados' },
  { iso: 'BH', nome: 'Barein' },
  { iso: 'BE', nome: 'Bélgica' },
  { iso: 'BZ', nome: 'Belize' },
  { iso: 'BJ', nome: 'Benin' },
  { iso: 'BY', nome: 'Bielorrússia' },
  { iso: 'BO', nome: 'Bolívia' },
  { iso: 'BA', nome: 'Bósnia e Herzegovina' },
  { iso: 'BW', nome: 'Botsuana' },
  { iso: 'BN', nome: 'Brunei' },
  { iso: 'BG', nome: 'Bulgária' },
  { iso: 'BF', nome: 'Burquina Faso' },
  { iso: 'BI', nome: 'Burundi' },
  { iso: 'BT', nome: 'Butão' },
  { iso: 'CV', nome: 'Cabo Verde' },
  { iso: 'CM', nome: 'Camarões' },
  { iso: 'KH', nome: 'Camboja' },
  { iso: 'CA', nome: 'Canadá' },
  { iso: 'QA', nome: 'Catar' },
  { iso: 'KZ', nome: 'Cazaquistão' },
  { iso: 'TD', nome: 'Chade' },
  { iso: 'CL', nome: 'Chile' },
  { iso: 'CN', nome: 'China' },
  { iso: 'CY', nome: 'Chipre' },
  { iso: 'VA', nome: 'Cidade do Vaticano' },
  { iso: 'CO', nome: 'Colômbia' },
  { iso: 'KM', nome: 'Comores' },
  { iso: 'CD', nome: 'Congo - Kinshasa' },
  { iso: 'KP', nome: 'Coreia do Norte' },
  { iso: 'KR', nome: 'Coreia do Sul' },
  { iso: 'CI', nome: 'Costa do Marfim' },
  { iso: 'CR', nome: 'Costa Rica' },
  { iso: 'HR', nome: 'Croácia' },
  { iso: 'CU', nome: 'Cuba' },
  { iso: 'DK', nome: 'Dinamarca' },
  { iso: 'DJ', nome: 'Djibuti' },
  { iso: 'DM', nome: 'Dominica' },
  { iso: 'EG', nome: 'Egito' },
  { iso: 'SV', nome: 'El Salvador' },
  { iso: 'AE', nome: 'Emirados Árabes Unidos' },
  { iso: 'EC', nome: 'Equador' },
  { iso: 'ER', nome: 'Eritreia' },
  { iso: 'SK', nome: 'Eslováquia' },
  { iso: 'SI', nome: 'Eslovênia' },
  { iso: 'ES', nome: 'Espanha' },
  { iso: 'SZ', nome: 'Essuatíni' },
  { iso: 'US', nome: 'Estados Unidos' },
  { iso: 'EE', nome: 'Estônia' },
  { iso: 'ET', nome: 'Etiópia' },
  { iso: 'FJ', nome: 'Fiji' },
  { iso: 'PH', nome: 'Filipinas' },
  { iso: 'FI', nome: 'Finlândia' },
  { iso: 'FR', nome: 'França' },
  { iso: 'GA', nome: 'Gabão' },
  { iso: 'GM', nome: 'Gâmbia' },
  { iso: 'GH', nome: 'Gana' },
  { iso: 'GE', nome: 'Geórgia' },
  { iso: 'GD', nome: 'Granada' },
  { iso: 'GR', nome: 'Grécia' },
  { iso: 'GT', nome: 'Guatemala' },
  { iso: 'GY', nome: 'Guiana' },
  { iso: 'GN', nome: 'Guiné' },
  { iso: 'GQ', nome: 'Guiné Equatorial' },
  { iso: 'GW', nome: 'Guiné-Bissau' },
  { iso: 'HT', nome: 'Haiti' },
  { iso: 'HN', nome: 'Honduras' },
  { iso: 'HU', nome: 'Hungria' },
  { iso: 'YE', nome: 'Iêmen' },
  { iso: 'MH', nome: 'Ilhas Marshall' },
  { iso: 'SB', nome: 'Ilhas Salomão' },
  { iso: 'IN', nome: 'Índia' },
  { iso: 'ID', nome: 'Indonésia' },
  { iso: 'IR', nome: 'Irã' },
  { iso: 'IQ', nome: 'Iraque' },
  { iso: 'IE', nome: 'Irlanda' },
  { iso: 'IS', nome: 'Islândia' },
  { iso: 'IL', nome: 'Israel' },
  { iso: 'IT', nome: 'Itália' },
  { iso: 'JM', nome: 'Jamaica' },
  { iso: 'JP', nome: 'Japão' },
  { iso: 'JO', nome: 'Jordânia' },
  { iso: 'KW', nome: 'Kuwait' },
  { iso: 'LA', nome: 'Laos' },
  { iso: 'LS', nome: 'Lesoto' },
  { iso: 'LV', nome: 'Letônia' },
  { iso: 'LB', nome: 'Líbano' },
  { iso: 'LR', nome: 'Libéria' },
  { iso: 'LY', nome: 'Líbia' },
  { iso: 'LI', nome: 'Liechtenstein' },
  { iso: 'LT', nome: 'Lituânia' },
  { iso: 'LU', nome: 'Luxemburgo' },
  { iso: 'MK', nome: 'Macedônia do Norte' },
  { iso: 'MG', nome: 'Madagascar' },
  { iso: 'MY', nome: 'Malásia' },
  { iso: 'MW', nome: 'Malaui' },
  { iso: 'MV', nome: 'Maldivas' },
  { iso: 'ML', nome: 'Mali' },
  { iso: 'MT', nome: 'Malta' },
  { iso: 'MA', nome: 'Marrocos' },
  { iso: 'MU', nome: 'Maurício' },
  { iso: 'MR', nome: 'Mauritânia' },
  { iso: 'MX', nome: 'México' },
  { iso: 'MM', nome: 'Mianmar (Birmânia)' },
  { iso: 'FM', nome: 'Micronésia' },
  { iso: 'MZ', nome: 'Moçambique' },
  { iso: 'MD', nome: 'Moldávia' },
  { iso: 'MC', nome: 'Mônaco' },
  { iso: 'MN', nome: 'Mongólia' },
  { iso: 'ME', nome: 'Montenegro' },
  { iso: 'NA', nome: 'Namíbia' },
  { iso: 'NR', nome: 'Nauru' },
  { iso: 'NP', nome: 'Nepal' },
  { iso: 'NI', nome: 'Nicarágua' },
  { iso: 'NE', nome: 'Níger' },
  { iso: 'NG', nome: 'Nigéria' },
  { iso: 'NO', nome: 'Noruega' },
  { iso: 'NZ', nome: 'Nova Zelândia' },
  { iso: 'OM', nome: 'Omã' },
  { iso: 'NL', nome: 'Países Baixos' },
  { iso: 'PW', nome: 'Palau' },
  { iso: 'PA', nome: 'Panamá' },
  { iso: 'PG', nome: 'Papua-Nova Guiné' },
  { iso: 'PK', nome: 'Paquistão' },
  { iso: 'PY', nome: 'Paraguai' },
  { iso: 'PE', nome: 'Peru' },
  { iso: 'PL', nome: 'Polônia' },
  { iso: 'PT', nome: 'Portugal' },
  { iso: 'KE', nome: 'Quênia' },
  { iso: 'KG', nome: 'Quirguistão' },
  { iso: 'KI', nome: 'Quiribati' },
  { iso: 'GB', nome: 'Reino Unido' },
  { iso: 'CF', nome: 'República Centro-Africana' },
  { iso: 'CG', nome: 'República do Congo' },
  { iso: 'DO', nome: 'República Dominicana' },
  { iso: 'RO', nome: 'Romênia' },
  { iso: 'RW', nome: 'Ruanda' },
  { iso: 'RU', nome: 'Rússia' },
  { iso: 'WS', nome: 'Samoa' },
  { iso: 'SM', nome: 'San Marino' },
  { iso: 'LC', nome: 'Santa Lúcia' },
  { iso: 'KN', nome: 'São Cristóvão e Névis' },
  { iso: 'ST', nome: 'São Tomé e Príncipe' },
  { iso: 'VC', nome: 'São Vicente e Granadinas' },
  { iso: 'SC', nome: 'Seicheles' },
  { iso: 'SN', nome: 'Senegal' },
  { iso: 'SL', nome: 'Serra Leoa' },
  { iso: 'RS', nome: 'Sérvia' },
  { iso: 'SG', nome: 'Singapura' },
  { iso: 'SY', nome: 'Síria' },
  { iso: 'SO', nome: 'Somália' },
  { iso: 'LK', nome: 'Sri Lanka' },
  { iso: 'SD', nome: 'Sudão' },
  { iso: 'SS', nome: 'Sudão do Sul' },
  { iso: 'SE', nome: 'Suécia' },
  { iso: 'CH', nome: 'Suíça' },
  { iso: 'SR', nome: 'Suriname' },
  { iso: 'TJ', nome: 'Tadjiquistão' },
  { iso: 'TH', nome: 'Tailândia' },
  { iso: 'TW', nome: 'Taiwan' },
  { iso: 'TZ', nome: 'Tanzânia' },
  { iso: 'CZ', nome: 'Tchéquia' },
  { iso: 'PS', nome: 'Territórios palestinos' },
  { iso: 'TL', nome: 'Timor-Leste' },
  { iso: 'TG', nome: 'Togo' },
  { iso: 'TO', nome: 'Tonga' },
  { iso: 'TT', nome: 'Trinidad e Tobago' },
  { iso: 'TN', nome: 'Tunísia' },
  { iso: 'TM', nome: 'Turcomenistão' },
  { iso: 'TR', nome: 'Turquia' },
  { iso: 'TV', nome: 'Tuvalu' },
  { iso: 'UA', nome: 'Ucrânia' },
  { iso: 'UG', nome: 'Uganda' },
  { iso: 'UY', nome: 'Uruguai' },
  { iso: 'UZ', nome: 'Uzbequistão' },
  { iso: 'VU', nome: 'Vanuatu' },
  { iso: 'VE', nome: 'Venezuela' },
  { iso: 'VN', nome: 'Vietnã' },
  { iso: 'ZM', nome: 'Zâmbia' },
  { iso: 'ZW', nome: 'Zimbábue' },
];

/**
 * Bandeira do pais a partir do codigo ISO.
 *
 * As duas letras viram os "indicadores regionais" do Unicode, que o sistema
 * desenha como bandeira. Sem imagem, sem CDN, sem dependencia.
 *
 * RESSALVA HONESTA: o Windows nao desenha bandeiras em emoji -- mostra as
 * duas letras (AR, PT, US). Nao e defeito nosso e nao quebra nada: do lado do
 * organizador continua sendo uma marca curta ao lado do nome. No celular
 * (iPhone e Android) a bandeira aparece normalmente.
 */
export const bandeiraDoPais = (iso) => {
  const codigo = String(iso || '').trim().toUpperCase();
  if (!/^[A-Z]{2}$/.test(codigo)) return '';
  return String.fromCodePoint(
    ...[...codigo].map(letra => 0x1F1E6 + letra.charCodeAt(0) - 65)
  );
};

/** Nome do pais em portugues, ou o proprio codigo se for desconhecido. */
export const nomeDoPais = (iso) => {
  const codigo = String(iso || '').trim().toUpperCase();
  const achado = NACIONALIDADES.find(p => p.iso === codigo);
  return achado ? achado.nome : codigo;
};

/** Ex.: "AR" -> "(bandeira) Argentina". Vazio quando nao ha nacionalidade. */
export const bandeiraENome = (iso) => {
  if (!iso) return '';
  return [bandeiraDoPais(iso), nomeDoPais(iso)].filter(Boolean).join(' ');
};
