export const WORK_AREAS = [
  "Contêiner",
  "Copa",
  "Cozinha",
  "Cracolândia",
  "Cristolandia",
  "Dia do arrebatamento da igreja",
  "Disponível para qualquer área 1",
  "Disponível para qualquer área 2",
  "Disponível para qualquer área 3",
  "Espírito Santo",
  "Falsa baiana",
  "Família",
  "Família muçulmana",
  "Fotografia",
  "Guia",
  "Hospital (Cena teatral)",
  "Igreja subterrânea",
  "Inimigo",
  "Invisível",
  "Logística",
  "Louvor nas cenas",
  "Marcador",
  "Oração Itinerante",
  "Pastor Enforcado",
  "Perseguidos",
  "Presídio",
  "Primeiros socorros - Saúde",
  "Recepção",
  "Segurança",
  "Selva",
  "Teatro",
  "Túmulo"
];

export const DEFAULT_AREA_CAPACITY = 5;