-- Migration: Add Missing Fields and Ensure Table Structure
-- Based on codebase analysis of Organizer Scale and Config modules

-- 1. Table: configuracoes
CREATE TABLE IF NOT EXISTS configuracoes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  max_equipantes INTEGER DEFAULT 0,
  max_acampantes INTEGER DEFAULT 0,
  numero_edicao INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Ensure all columns exist (idempotent checks)
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'configuracoes' AND column_name = 'max_equipantes') THEN
    ALTER TABLE configuracoes ADD COLUMN max_equipantes INTEGER DEFAULT 0;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'configuracoes' AND column_name = 'max_acampantes') THEN
    ALTER TABLE configuracoes ADD COLUMN max_acampantes INTEGER DEFAULT 0;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'configuracoes' AND column_name = 'numero_edicao') THEN
    ALTER TABLE configuracoes ADD COLUMN numero_edicao INTEGER DEFAULT 0;
  END IF;
END $$;


-- 2. Table: configuracoes_inscricoes
CREATE TABLE IF NOT EXISTS configuracoes_inscricoes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  inscricoes_equipantes BOOLEAN DEFAULT TRUE,
  inscricoes_acampantes BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'configuracoes_inscricoes' AND column_name = 'inscricoes_equipantes') THEN
    ALTER TABLE configuracoes_inscricoes ADD COLUMN inscricoes_equipantes BOOLEAN DEFAULT TRUE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'configuracoes_inscricoes' AND column_name = 'inscricoes_acampantes') THEN
    ALTER TABLE configuracoes_inscricoes ADD COLUMN inscricoes_acampantes BOOLEAN DEFAULT TRUE;
  END IF;
END $$;


-- 3. Table: limites_areas
CREATE TABLE IF NOT EXISTS limites_areas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  area_nome TEXT NOT NULL UNIQUE,
  limite_maximo INTEGER DEFAULT 5,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Add index for faster lookups by name
CREATE INDEX IF NOT EXISTS idx_limites_areas_nome ON limites_areas(area_nome);


-- 4. Table: escalas
CREATE TABLE IF NOT EXISTS escalas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  equipante_id UUID NOT NULL,
  equipante_nome TEXT, -- Denormalized for display convenience
  area_alocada TEXT NOT NULL,
  is_manual BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(equipante_id) -- Ensure one allocation per equipante
);

-- Add index for fetching by area
CREATE INDEX IF NOT EXISTS idx_escalas_area ON escalas(area_alocada);

-- Add foreign key constraint if equipantes table exists
DO $$ 
BEGIN 
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'equipantes') THEN
    BEGIN
      ALTER TABLE escalas 
      ADD CONSTRAINT fk_escalas_equipante 
      FOREIGN KEY (equipante_id) 
      REFERENCES equipantes(id) 
      ON DELETE CASCADE;
    EXCEPTION
      WHEN duplicate_object THEN NULL;
    END;
  END IF;
END $$;