-- Complete Database Schema Migration for Metanoia Radical
-- Includes all tables, columns, constraints, and indexes found in the codebase.
-- Idempotent script: Safe to run multiple times.

-- ============================================================================
-- 1. CONFIGURACOES
-- Used in: src/lib/organizerHelpers.js
-- ============================================================================
CREATE TABLE IF NOT EXISTS configuracoes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    max_equipantes INTEGER DEFAULT 0,
    max_acampantes INTEGER DEFAULT 0,
    edicao_numero INTEGER DEFAULT 0,
    observacoes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure only one row exists (Singleton pattern logic usually handled by app, but we insert default if empty)
INSERT INTO configuracoes (id, max_equipantes, max_acampantes, edicao_numero, observacoes)
SELECT 1, 0, 0, 1, 'Configuração Inicial'
WHERE NOT EXISTS (SELECT 1 FROM configuracoes);

-- ============================================================================
-- 2. INSCRICOES_STATUS
-- Used in: src/lib/organizerHelpers.js
-- ============================================================================
CREATE TABLE IF NOT EXISTS inscricoes_status (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    inscricoes_equipantes BOOLEAN DEFAULT TRUE,
    inscricoes_acampantes BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default row if empty
INSERT INTO inscricoes_status (id, inscricoes_equipantes, inscricoes_acampantes)
SELECT '00000000-0000-0000-0000-000000000001', TRUE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM inscricoes_status);

-- ============================================================================
-- 3. USERS (Public Role Management)
-- Used in: src/hooks/useOrganizerAuth.js
-- ============================================================================
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY REFERENCES auth.users(id),
    email TEXT,
    role TEXT DEFAULT 'user', -- 'organizador', 'equipante', 'acampante', 'parceiro'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- 4. EQUIPANTES
-- Used in: src/lib/equipanteHelpers.js, src/lib/api/equipanteApi.js, etc.
-- ============================================================================
CREATE TABLE IF NOT EXISTS equipantes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add all columns idempotent-ly
DO $$
BEGIN
    -- Core & Metadata
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pendente';
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS tipo TEXT DEFAULT 'equipante';
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS numero_edicao INTEGER;
    
    -- Personal Data
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS nome TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS nome_completo TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS cpf TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS data_nascimento DATE;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS genero TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS sexo TEXT; -- Alias often used
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS estado_civil TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS profissao TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS tamanho_camisa TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS tamanho_camiseta TEXT; -- Alias often used
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS email TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS whatsapp TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS telefone TEXT; -- Alias
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS telefone_residencial TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS idade INTEGER;
    
    -- Address
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS cep TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS endereco TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS numero TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS complemento TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS bairro TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS cidade TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS estado TEXT;
    
    -- Health
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS tem_problema_saude BOOLEAN DEFAULT FALSE;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS condicoes_medicas TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS usa_medicamento BOOLEAN DEFAULT FALSE;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS medicamentos TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS tem_restricao_alimentar BOOLEAN DEFAULT FALSE;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS restricoes_alimentares TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS esta_gravida BOOLEAN DEFAULT FALSE;
    
    -- Ecclesiastical
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS igreja TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS nome_igreja TEXT; -- Alias
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS e_pastor BOOLEAN DEFAULT FALSE;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS e_pastor_outro TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS pastor_nome TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS esta_afastado BOOLEAN DEFAULT FALSE;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS cargo_igreja TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS cargo_igreja_outro TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS frequenta_ebd BOOLEAN DEFAULT FALSE;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS frequenta_grupo_cuidado BOOLEAN DEFAULT FALSE;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS voce_canta BOOLEAN DEFAULT FALSE;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS toca_instrumento BOOLEAN DEFAULT FALSE;
    
    -- Complementary / Family
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS familiar_trabalhando BOOLEAN DEFAULT FALSE;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS familiar_trabalhando_outro TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS parentesco TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS familiar_nome TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS qual_radical_acampante TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS qual_radical_acampante_outro TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS numero_edicao_participou TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS ja_trabalhou_equipe BOOLEAN DEFAULT FALSE;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS edicao_trabalhou TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS deseja_trabalhar_edicao TEXT;
    
    -- Auth & Experience
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS autorizacao_imagem BOOLEAN DEFAULT FALSE;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS experiencia_acampamento TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS motivacao TEXT;
    
    -- Emergency
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS contato_emergencia_nome TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS contato_emergencia_telefone TEXT;
    
    -- Work Areas
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS area_trabalho_opcao1 TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS area_trabalho_opcao2 TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS area_trabalho_opcao3 TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS area_trabalho_extra TEXT;
    
    -- Payment (General + Stripe)
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS forma_pagamento TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS pagamento_dinheiro_descricao TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS status_pagamento TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS metodo_pagamento TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS metodo_pagamento_stripe TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS id_transacao_sicoob TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS id_transacao_stripe TEXT;
    ALTER TABLE equipantes ADD COLUMN IF NOT EXISTS data_pagamento TIMESTAMPTZ;
END $$;

-- Indexes for Equipantes
CREATE INDEX IF NOT EXISTS idx_equipantes_cpf ON equipantes(cpf);
CREATE INDEX IF NOT EXISTS idx_equipantes_status ON equipantes(status);
CREATE INDEX IF NOT EXISTS idx_equipantes_stripe ON equipantes(id_transacao_stripe);
CREATE INDEX IF NOT EXISTS idx_equipantes_edicao ON equipantes(numero_edicao);


-- ============================================================================
-- 5. ACAMPANTES
-- Used in: src/lib/acampanteHelpers.js, src/lib/api/inscricaoApi.js, etc.
-- ============================================================================
CREATE TABLE IF NOT EXISTS acampantes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add all columns idempotent-ly
DO $$
BEGIN
    -- Core & Metadata
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'aprovado';
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS tipo TEXT DEFAULT 'acampante';
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS numero_edicao INTEGER;

    -- Personal Data
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS nome TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS nome_completo TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS cpf TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS email TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS whatsapp TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS data_nascimento DATE;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS genero TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS estado_civil TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS profissao TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS tamanho_camisa TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS idade INTEGER;
    
    -- Address
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS cep TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS endereco TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS numero TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS complemento TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS bairro TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS cidade TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS estado TEXT;
    
    -- Health
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS tem_problema_saude BOOLEAN DEFAULT FALSE;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS problemas_saude BOOLEAN DEFAULT FALSE; -- Alias for code compatibility
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS condicoes_medicas TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS usa_medicamento BOOLEAN DEFAULT FALSE;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS usa_medicamentos BOOLEAN DEFAULT FALSE; -- Alias for code compatibility
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS medicamentos TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS tem_restricao_alimentar BOOLEAN DEFAULT FALSE;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS restricoes_alimentares TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS esta_gravida BOOLEAN DEFAULT FALSE;
    
    -- Ecclesiastical
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS igreja TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS pastor_nome TEXT;
    
    -- Admin / Referral
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS admin_responsavel TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS codigo_admin TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS quem_indicou_nome TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS quem_indicou_telefone TEXT;
    
    -- Emergency
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS contato_emergencia_nome TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS contato_emergencia_telefone TEXT;
    
    -- Legal
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS autorizacao_imagem BOOLEAN DEFAULT FALSE;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS termo_responsabilidade_aceito BOOLEAN DEFAULT FALSE;
    
    -- Payment (General + Stripe)
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS forma_pagamento TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS status_pagamento TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS metodo_pagamento TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS metodo_pagamento_stripe TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS id_transacao_sicoob TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS id_transacao_stripe TEXT;
    ALTER TABLE acampantes ADD COLUMN IF NOT EXISTS data_pagamento TIMESTAMPTZ;
END $$;

-- Indexes for Acampantes
CREATE INDEX IF NOT EXISTS idx_acampantes_cpf ON acampantes(cpf);
CREATE INDEX IF NOT EXISTS idx_acampantes_status ON acampantes(status);
CREATE INDEX IF NOT EXISTS idx_acampantes_stripe ON acampantes(id_transacao_stripe);
CREATE INDEX IF NOT EXISTS idx_acampantes_edicao ON acampantes(numero_edicao);


-- ============================================================================
-- 6. LIMITES_AREAS
-- Used in: src/lib/limiteAreasHelpers.js
-- ============================================================================
CREATE TABLE IF NOT EXISTS limites_areas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    area_nome TEXT UNIQUE NOT NULL,
    limite_maximo INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================================
-- 7. ESCALAS
-- Used in: src/lib/organizerHelpers.js
-- ============================================================================
CREATE TABLE IF NOT EXISTS escalas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    equipante_id UUID REFERENCES equipantes(id),
    equipante_nome TEXT, -- Denormalized for easier query
    area_alocada TEXT,
    is_manual BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Constraint to ensure one allocation per equipante per edition (if extended logic applied)
-- For now, just a unique constraint on equipante_id
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'escalas_equipante_id_key') THEN
        ALTER TABLE escalas ADD CONSTRAINT escalas_equipante_id_key UNIQUE (equipante_id);
    END IF;
END $$;


-- ============================================================================
-- 8. PAYMENT_INFO
-- Used in: src/lib/paymentHelpers.js
-- ============================================================================
CREATE TABLE IF NOT EXISTS payment_info (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID, -- Optional link to auth.users
    inscription_id UUID, -- Link to equipantes or acampantes ID manually
    payment_method TEXT,
    amount DECIMAL(10,2),
    status TEXT,
    transaction_id TEXT,
    pix_copy_paste TEXT,
    boleto_barcode TEXT,
    boleto_url TEXT,
    confirmed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);