-- Migration: Importa limites de inscricao por igreja (planilha da usuaria)
-- Date: 2026-09-10
--
-- Fonte: "victoria tabela mr_administrador.xlsx" (146 igrejas, coluna
-- mra_nome_administrador + mra_qtd_vagas), cruzada com a lista atual de
-- igrejas (IGREJAS_PARCEIRAS / nova_tabela_igrejas.xlsx, ja aplicada em
-- 2026-09-10) pra montar a chave exata "NN - Nome" que a tabela
-- limites_igrejas usa (mesmo texto que aparece no seletor "Igreja
-- Responsavel pela Inscricao" do formulario).
--
-- Cobre 144 das 146 igrejas. "144 - IGREJA METODISTA CAMPUS ALBUQUERQUE"
-- nao tinha limite na planilha original -- usuaria confirmou depois: 5
-- vagas (ja incluido abaixo). Faltam so as 2 igrejas com nome duplicado:
-- "23 - BATISTA EM TERESOPOLIS" e "129 - BATISTA EM TERESOPOLIS" sao duas
-- igrejas distintas na lista oficial com o MESMO nome, e a planilha de
-- limites tambem tem duas linhas "BATISTA EM TERESOPOLIS" (vagas 3 e
-- vagas 5) sem indicar qual e qual -- usuaria vai conferir e confirmar.
--
-- Roda um UPSERT (ON CONFLICT no texto da igreja) em vez de INSERT puro,
-- pra nao duplicar caso alguma dessas 143 ja tenha uma excecao
-- configurada manualmente -- nesse caso o valor da planilha simplesmente
-- sobrescreve o que estava la.
INSERT INTO limites_igrejas (igreja, limite_maximo, updated_at) VALUES
  ('01 - MINISTÉRIO ARCA DA ALIANÇA', 5, now()),
  ('02 - COMUNIDADE KADOSH', 4, now()),
  ('03 - IGREJAS DE PETRÓPOLIS', 15, now()),
  ('04 - MISSIONÁRIA NOVO ISRAEL', 2, now()),
  ('05 - ASSEMBLEIA DE DEUS CAMINHO CELESTE', 3, now()),
  ('06 - METODISTA EM SERRA DO CAPIM', 3, now()),
  ('07 - ASSEMBLEIA DE DEUS CENTRO MISSIONÁRIO CRISTÃO', 2, now()),
  ('08 - METODISTA CASA FAVORITA - RESENDE', 6, now()),
  ('09 - ASSEMBLEIA DE DEUS DE VARGEM GRANDE CONGREGAÇÃO SERRINHA', 3, now()),
  ('10 - IGREJA DE DEUS EM PIMENTEIRAS', 4, now()),
  ('11 - METODISTA EM OLARIA - NOVA FRIBURGO RJ', 4, now()),
  ('12 - PENTECOSTAL RENASCENDO DAS CINZAS', 2, now()),
  ('13 - NOVA ASSEMBLEIA DE DEUS EM TERESÓPOLIS', 7, now()),
  ('14 - PIB EM VIEIRA TERESÓPOLIS', 5, now()),
  ('15 - MINISTÉRIO DA FÉ.', 3, now()),
  ('16 - IGREJA DE CRISTO EM TERESÓPOLIS', 5, now()),
  ('17 - ASSEMBLEIA DE DEUS DE TERESÓPOLIS - SEDE', 8, now()),
  ('18 - ASSEMBLEIA DE DEUS DE TERESÓPOLIS - SUBSEDE SÃO PEDRO', 5, now()),
  ('19 - ASSEMBLEIA DE DEUS DE TERESÓPOLIS - SUBSEDE PESSEGUEIROS', 3, now()),
  ('20 - ASSEMBLEIA DE DEUS DE TERESÓPOLIS - SUBSEDE BARRA IMBUÍ', 5, now()),
  ('21 - PRIMEIRA IGREJA BATISTA DE BONSUCESSO PIBB', 5, now()),
  ('22 - MINISTÉRIO PROFÉTICO KEMUEL.', 2, now()),
  ('24 - FILADELFIA', 1, now()),
  ('25 - METODISTA NOVA SUÍÇA', 4, now()),
  ('26 - MISSIONARIA EVANGELICA DEUS É PRIORIDADE', 2, now()),
  ('27 - HEBROM CHURCH', 6, now()),
  ('28 - JESUS É ALIANCA', 5, now()),
  ('29 - JESURUM', 3, now()),
  ('30 - COMUNIDADE EVANGÉLICA MINISTÉRIO INTERNACIONAL ALIANÇA EM CRISTO', 3, now()),
  ('31 - AD NOVA GERAÇÃO CEMAE', 4, now()),
  ('32 - BATISTA EM BARRA DO IMBUI', 3, now()),
  ('33 - MINISTERIO FAMILIA EM GRAÇA', 0, now()),
  ('34 - AD FAMÍLIA EM CRISTO.', 1, now()),
  ('35 - PROJETO SEMEAR EM CRUZEIRO', 0, now()),
  ('36 - METODISTA DE MACUCO', 0, now()),
  ('37 - BATISTA BETEL EM VENDA NOVA', 3, now()),
  ('38 - ASSEMBLEIA DE DEUS MINISTÉRIO FORÇA E HONRA', 2, now()),
  ('39 - ASSEMBLEIA DE DEUS NO MEUDON', 3, now()),
  ('40 - ASSEMBLEIA DE DEUS VINDE A MIM RIO DAS OSTRAS', 5, now()),
  ('41 - PENTECOSTAL JUSTIFICADOS PELA FÉ', 4, now()),
  ('42 - METODISTA DE VARGEM GRANDE', 5, now()),
  ('43 - PRESBITERIANA DO MEUDON', 5, now()),
  ('44 - METODISTA EM CAMPO DO COELHO', 4, now()),
  ('45 - NOVA IGREJA DE CRISTO DA BARRA', 4, now()),
  ('46 - BATISTA DE SOLEDADE', 4, now()),
  ('47 - JAT MEUDON', 8, now()),
  ('48 - BATISTA MONTE DAS OLIVEIRAS -MISSÃO CORÉIA.', 3, now()),
  ('49 - ASSEMBLEIA DE DEUS DA CASCATA DO IMBUÍ.', 4, now()),
  ('50 - PENTECOSTAL TABERNÁCULO DA GRAÇA ÁGUA QUENTE', 3, now()),
  ('51 - ASSEMBLEIA DE DEUS VISÃO MISSIONÁRIA (ADVM)', 3, now()),
  ('52 - JAT - SEDE', 10, now()),
  ('53 - CASA DO PAI', 7, now()),
  ('54 - BATISTA EBENEZER EM MOTAS', 2, now()),
  ('55 - CARA DE LEÃO DUQUE DE CAXIAS', 7, now()),
  ('56 - MINISTÉRIO DEUS DAR VIDA', 3, now()),
  ('57 - BATISTA DA FAMÍLIA EM BONSUCESSO', 3, now()),
  ('58 - BATISTA MONTE DAS OLIVEIRAS SEDE', 2, now()),
  ('59 - MINISTÉRIO BENDITO EU SOU.', 8, now()),
  ('60 - CARA DE LEÃO TERESÓPOLIS', 5, now()),
  ('61 - PRIMEIRA IGREJA BATISTA EM VARGEM GRANDE', 3, now()),
  ('62 - CASA DE ORAÇÃO SÃO PEDRO', 6, now()),
  ('63 - COPETE', 2, now()),
  ('64 - METODISTA CENTENÁRIO', 25, now()),
  ('65 - COMUNIDADE PENTECOSTAL É HORA DE AVIVAMENTO', 3, now()),
  ('66 - PRESBITERIANA MONTE MORIAH', 4, now()),
  ('67 - UNIDOS PELA FE EM DEUS', 5, now()),
  ('68 - BATISTA JERUEL', 2, now()),
  ('69 - COMUNIDADE EVANGÉLICA VIDA EM COMUNHÃO', 5, now()),
  ('70 - MINISTÉRIO APOSTÓLICO CASA DE LOUVOR', 3, now()),
  ('71 - BATISTA DE BALANÇA', 4, now()),
  ('72 - ASSEMBLEIA DE DEUS CENTRO CRISTÃO MISSIONÁRIO EM VIEIRA', 5, now()),
  ('73 - CRISTÃ MUNDIAL', 5, now()),
  ('74 - JAT – CONGREGAÇÃO UNAMAR', 3, now()),
  ('75 - MINISTÉRIO VINDE A MIM – CASIMIRO DE ABREU', 4, now()),
  ('76 - CONGREGAÇÃO METODISTA PRATA', 2, now()),
  ('77 - BATISTA SERRA DOS ÓRGÃOS', 4, now()),
  ('78 - METODISTA CENTRAL', 50, now()),
  ('79 - BRASIL PARA CRISTO', 4, now()),
  ('80 - METODISTA EM BONSUCESSO', 0, now()),
  ('81 - ASSEMBLEIA DE DEUS MINISTERIO BETEL', 3, now()),
  ('82 - CASA DO LEÃO', 5, now()),
  ('83 - PROJETO SEMEAR SANTA CECÍLIA', 3, now()),
  ('84 - DIVERSOS', 120, now()),
  ('85 - MISSÃO METODISTA MEUDON', 4, now()),
  ('86 - BATISTA NOVA CANAÃ', 3, now()),
  ('87 - CONGREGAÇÃO CRISTÃO ATITUDE FÉ', 4, now()),
  ('88 - METODISTA EM CORDEIRO', 2, now()),
  ('89 - ASSEMBLEIA DE DEUS DA FAMÍLIA', 3, now()),
  ('90 - ASSEMBLEIA DE DEUS CELEBRANDO AO SENHOR', 2, now()),
  ('91 - ASSEMBLEIA DEUS MONTE CARMELO', 3, now()),
  ('92 - BATISTA EM AGUA QUENTE', 2, now()),
  ('93 - PENTECOTAL JESUS É O CAMINHO DEUS É O SENHOR', 3, now()),
  ('94 - ASSEMBLEIA DE DEUS IDE - SJVRP', 5, now()),
  ('95 - ASSEMBLEIA DE DEUS EM SALINAS', 4, now()),
  ('96 - METODISTA CENTENÁRIO CAMPUS CORÉIA', 4, now()),
  ('97 - JAT - PIMENTEL', 3, now()),
  ('98 - COMUNIDADE INTERNACIONAL GENESIS', 3, now()),
  ('99 - ASSEMBLEIA DE DEUS RESTAURAR', 1, now()),
  ('100 - IGREJA DAS NAÇÕES', 3, now()),
  ('101 - METODISTA EM VILA DO PIÃO', 2, now()),
  ('102 - METODISTA EM ANDORINHAS', 3, now()),
  ('103 - BATISTA APARECIDA', 2, now()),
  ('104 - MINISTÉRIO RECOMEÇAR EM CRISTO', 3, now()),
  ('105 - ADEC', 3, now()),
  ('106 - ASSEMBLEIA DE DEUS NOVA ALIANÇA COM CRISTO', 5, now()),
  ('107 - ASSEMBLEIA DE DEUS DO UNIVERSO', 5, now()),
  ('108 - BATISTA JERUEL PETROPOLIS', 2, now()),
  ('109 - BATISTA AGUA VIVA', 3, now()),
  ('110 - EDIÇÕES ANTERIORES', 10, now()),
  ('111 - BATISTA EM RENOVAÇÃO ESPIRITUAL MONTE SINAI', 3, now()),
  ('112 - ASSEMBLEIA DE DEUS MINISTÉRIO INTEGRAÇÃO', 4, now()),
  ('113 - COMUNIDADE É TEMPLO DA FÉ', 4, now()),
  ('114 - ASSEMBLEIA DO AMOR', 4, now()),
  ('115 - SEGUNDA IGREJA BATISTA DO MEUDON', 4, now()),
  ('116 - A CASA DO MESTRE', 5, now()),
  ('117 - ASSEMBLEIA DE DEUS ADORAI', 3, now()),
  ('118 - CASA DE ORAÇÃO VIDEIRA', 2, now()),
  ('119 - CONGREGACIONAL VEM VIVER', 3, now()),
  ('120 - BATISTA NO BATUME', 4, now()),
  ('121 - ASSEMBLEIA DE DEUS FILADÉLFIA', 3, now()),
  ('122 - BRASIL PARA CRISTO DE PIÃO', 5, now()),
  ('123 - MINISTERIO AJOELHAR', 2, now()),
  ('124 - ESPAÇO VIDA', 10, now()),
  ('125 - COLHEITA CHURCH', 3, now()),
  ('126 - PENTECOSTAL RESTAURAÇÃO DIVINA', 3, now()),
  ('127 - COMUNIDADE CRISTÃ ENCONTRO ROSÁRIO', 1, now()),
  ('128 - BATISTA JERUEL EM SAPUCAIA', 2, now()),
  ('130 - LUUZ CHURCH', 2, now()),
  ('131 - JAT - QUINTA LEBRÃO', 0, now()),
  ('132 - ASSASSEMBLEIA DE DEUS MINISTÉRIO VINDE A MIM UNAMAR', 1, now()),
  ('133 - ASSEMBLEIA DE DEUS PEDRA DE DAVI', 4, now()),
  ('134 - VIDA ABUNDANTE', 4, now()),
  ('135 - IGREJA PENTECOSTAL ICTHUS', 5, now()),
  ('136 - IGREJA BATISTA DE MOTTAS', 3, now()),
  ('137 - ASSEMBLEIA DE DEUS PENTECOSTE VIVO', 4, now()),
  ('138 - IGREJA BATISTA DO RECREIO DOS BANDEIRANTES RJ', 5, now()),
  ('139 - BATISTA RENOVADA JERUEL EM SÃO JOSÉ DO VALE DO RIO PRETO', 6, now()),
  ('140 - IGREJA PENTECOATAL CRISTO ESPERANÇA NOSSA', 4, now()),
  ('141 - IGREJA BATISTA DO ALTO', 4, now()),
  ('142 - IGREJA BATISTA NOVA FILADÉLFIA', 4, now()),
  ('143 - IGREJA NOVOS COMEÇOS', 2, now()),
  ('144 - IGREJA METODISTA CAMPUS ALBUQUERQUE', 5, now()),
  ('145 - PARQUE FLUMINENSE BELFORD ROXO', 4, now()),
  ('146 - BATISTA JERUEL TRÊS RIOS', 4, now())
ON CONFLICT (igreja) DO UPDATE SET
  limite_maximo = EXCLUDED.limite_maximo,
  updated_at = EXCLUDED.updated_at;
